name: azure_application_insights
description: A Dart client for Azure's Application Insights service
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  uuid: ^2.2.2

dev_dependencies:
  mockito: ^4.1.1
  pedantic: ^1.8.0
  quiver: ^2.1.5
  test: ^1.6.0
